from typing import Final

MAX_QUADRANT_SECTOR_XY: Final[int] = 8
MAX_STARSPERQUADRANT: Final[int] = 5

ENEMY_ZERO_ONE: Final[int] = 75
ENEMY_ONE_TWO: Final[int] = 90
ENEMY_TWO_THREE: Final[int] = 96

MISSION_TIME_PER_ENEMY_RATIO: Final[float] = 2.0

STARBASE_CHANCE: Final[int] = 95

ENEMY_MOVE_CHANCE: Final[int] = 85

LRS_RANGE: Final[int]  = 1
MAX_STARSHIP_ENERGY: Final[int] = 3000
MAX_STARSHIP_TORP: Final [int]  = 10
SECTOR_TO_ENERGY_CONV: Final[int] = 4
LASER_MISS_CHANCE_CPU_DOWN: Final[int] = 60
STAR_DESTROYED_CHANCE: Final[int] = 80
DAMAGE_DEVICE_RANDOM_NUMBER_THRESHOLD: Final[int] = 85
SECTOR_TO_TIME_CONV: Final[float] = 0.01
MAX_DAMAGE_MISSION_TIME_AMOUNT: Final[int] = 4
SHE_ERRORMESSAGE: Final[str] = "Insufficient Energy"
SHE_INVALIDAMOUNT: Final[str] = "Inalid Energy Amount"
LAS_INVALIDAMOUNT: Final[str] = "Inalid Energy Amount"
SECTOR_EMPTY: Final[str] = "EMPTY"
SECTOR_STARSHIP: Final[str] = "STARSHIP"
SECTOR_STAR: Final[str] = "STAR"
SECTOR_STARBASE: Final[str] = "STARBASE"
SECTOR_ENEMY: Final[str] = "ENEMY"

RIT_DAMAGE_DEVICE = "DAMDEVICE"
RIT_DAMAGE_DEVICE_AMOUNT = "DAMDEVICEAMT"
RIT_DAMAGE_DEVICE_CHANCE = "DAMDEVICECHANCE"
RIT_ENEMY_CHANCE = "ENEMYCHANCE"
RIT_STAR_QUANTITY = "STARQUANTITY"
RIT_STARBASE_CHANCE = "STARBASECHANCE"
RIT_ENEMY_SHIELD_LEVEL = "ENEMYSHIELDLEVEL"
RIT_ENEMY_FIRED_AMOUNT = "ENEMYFIREDAMOUNT"
RIT_ENEMY_MOVE_CHANCE = "ENEMYMOVECHANCE"
RIT_STAR_DESTROYED_CHANCE = "STARDESTROYEDCHANCE"
RIT_LASER_MISS_CHANCE = "LASERMISCHANCE"
RIT_STARTING_MISSION_TIME = "STARTMISSION_TIME"

RCT_STARSHIP_SECTOR = "STARSHIPSECTOR"
RCT_STARSHIP_QUADRANT = "STARSHIPQUADRANT"
RCT_ENEMY_LOCATION = "ENEMYLOCATION"
RCT_STARBASE_LOCATION = "STARBASELOCATION"
RCT_STAR_LOCATION = "STARLOCATION"

